# Generated by Django 6.0.7 on 2026-08-28 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_department_pipelinestage_tag_alter_candidate_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('kind', models.CharField(choices=[('candidates', 'Candidates'), ('jobs', 'Jobs')], max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('query', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('auto_import', models.BooleanField(default=False)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('last_result_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'saved searches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SourcingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('candidates', 'Candidates'), ('jobs', 'Jobs')], max_length=20)),
                ('provider', models.CharField(max_length=50)),
                ('external_id', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, default='', max_length=400)),
                ('location', models.CharField(blank=True, default='', max_length=150)),
                ('url', models.URLField(blank=True, default='')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('new', 'New'), ('imported', 'Imported'), ('dismissed', 'Dismissed')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('imported_candidate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_results', to='candidates.candidate')),
                ('imported_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sourcing_results', to='candidates.job')),
                ('saved_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='candidates.savedsearch')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'unique_together': {('kind', 'provider', 'external_id')},
            },
        ),
    ]
